# Generated by Django 4.0.2 on 2022-02-25 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_bookpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.bookpage')),
                ('to_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_page', to='book.bookpage')),
            ],
            options={
                'unique_together': {('from_page', 'to_page')},
            },
        ),
    ]
