# Generated by Django 4.0.2 on 2022-02-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_pagelink'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='name',
            field=models.TextField(default='???'),
            preserve_default=False,
        ),
    ]
