# Generated by Django 4.0.2 on 2022-02-26 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_pagelink_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='first_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='first_page', to='book.bookpage'),
        ),
    ]
