# Generated by Django 4.0.2 on 2022-02-26 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_first_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(null=True, upload_to='uploads/'),
        ),
    ]
