# Generated by Django 4.0.2 on 2022-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0008_item_bookprogress_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookpage',
            name='items',
            field=models.ManyToManyField(to='book.Item'),
        ),
    ]
