# Generated by Django 4.0.2 on 2022-03-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_bookpage_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagelink',
            name='items',
            field=models.ManyToManyField(to='book.Item'),
        ),
    ]
